import React, { useState } from "react";
import "./Home.css";
import { Link } from "react-router-dom";
import { Select } from "antd";
import { CaretDownOutlined } from "@ant-design/icons";
import ArtistOfTheMonth from "../../Components/ArtistOfTheMonth/ArtistOfTheMonth";
import FeatureGallery from "../../Components/FeatureGallery/FeatureGallery";
import Slider from "react-slick";
import Artwork from "../../Components/Artwork/Artwork";
import Advertisement from "../../Components/Advertisement/Advertisement";
import Background from "../../Components/Assets/RectangleBackGround.svg";
import Gift from "../../Components/Assets/—Pngtree—cartoon ribbon gift card_4712732.svg";
import MD10 from "../../Components/Assets/coaster Md 10 cm.svg";
import Image29 from "../../Components/Assets/Rectangle 29.svg";
import Topics from "../../Components/BlogTopics/Topics";

const Home = () => {
  return (
    <div className="home">
      <div>
        <div
          id="carouselExampleIndicators"
          className="carousel slide"
          data-bs-ride="carousel"
        >
          <div className="carousel-indicators pt-3">
            <button
              type="button"
              data-bs-target="#carouselExampleIndicators"
              data-bs-slide-to="1"
              aria-label="Slide 2"
            ></button>
            <button
              type="button"
              data-bs-target="#carouselExampleIndicators"
              data-bs-slide-to="2"
              aria-label="Slide 3"
            ></button>
            <button
              type="button"
              data-bs-target="#carouselExampleIndicators"
              data-bs-slide-to="0"
              className="active"
              aria-current="true"
              aria-label="Slide 1"
            ></button>
            <button
              type="button"
              data-bs-target="#carouselExampleIndicators"
              data-bs-slide-to="3"
              aria-label="Slide 4"
            ></button>
            <button
              type="button"
              data-bs-target="#carouselExampleIndicators"
              data-bs-slide-to="4"
              aria-label="Slide 5"
            ></button>
          </div>
          <div className="carousel-inner">
            <div className="carousel-item ">
              <img
                src={Background}
                className="card-img d-block w-100"
                alt="..."
              />
              <div className="carousel-caption d-none d-md-block">
                <h1 className="card-title text-center mt-4">
                  Decorative Coasters Made With Artificial Intelligence
                </h1>
                <h4 className="card-text text-center">
                  A Collection Of Art - Ceated By Artists Around The World -
                  Generated By
                </h4>
                <h4 className="card-text text-center">
                  Al - Printed On High Quality Coasters.
                </h4>
                <Link to="#" className="btn-read">
                  <button className="btn-primary">READ MORE</button>
                </Link>
                <div className="mb-3 mt-5 d-flex justify-content-center">
                  <div className="d-block">
                    <div className="d-flex">
                      <Select
                        defaultValue="Colour"
                        allowClear
                        options={[
                          {
                            value: "Brown",
                            label: "Brown",
                          },
                          {
                            value: "Black",
                            label: "Black",
                          },
                          {
                            value: "Blue",
                            label: "Blue",
                          },
                          {
                            value: "Green",
                            label: "Green",
                          },
                          {
                            value: "Yellow",
                            label: "Yellow",
                          },
                          {
                            value: "Orange",
                            label: "Orange",
                          },
                          {
                            value: "Red",
                            label: "Red",
                          },
                          {
                            value: "Pink",
                            label: "Pink",
                          },
                          {
                            value: "Purple",
                            label: "Purple",
                          },
                        ]}
                      />
                    </div>
                    <div className="d-flex my-2">
                      <Select
                        defaultValue="Subject"
                        allowClear
                        options={[
                          {
                            value: "Landscapes & Sea and Sky",
                            label: "Landscapes & Sea and Sky",
                          },
                          {
                            value: "People",
                            label: "People",
                          },
                          {
                            value: "Animals and Birds",
                            label: "Animals and Birds",
                          },
                          {
                            value: "Abstract",
                            label: "Abstract",
                          },
                          {
                            value: "Still Life",
                            label: "Still Life",
                          },
                          {
                            value: "Architecture and Buildings",
                            label: "Architecture and Buildings",
                          },
                          {
                            value: "Flowers and Plants",
                            label: "Flowers and Plants",
                          },
                          {
                            value: "Nudes and Erotic",
                            label: "Nudes and Erotic",
                          },
                          {
                            value: "Transport",
                            label: "Transport",
                          },
                          {
                            value: "Dogs",
                            label: "Dogs",
                          },
                          {
                            value: "Cats",
                            label: "Cats",
                          },
                          {
                            value: "Horses",
                            label: "Horses",
                          },
                          {
                            value: "London Art",
                            label: "London Art",
                          },
                          {
                            value: "Office Wall Art",
                            label: "Office Wall Art",
                          },
                          {
                            value: "Art for Interior Designers",
                            label: "Art for Interior Designers",
                          },
                          {
                            value: "Nature",
                            label: "Nature",
                          },
                          {
                            value: "Sunsets",
                            label: "Sunsets",
                          },
                          {
                            value: "Cityscapes",
                            label: "Cityscapes",
                          },
                        ]}
                      />
                    </div>
                    <div className="d-flex my-2">
                      <Select
                        defaultValue="Style"
                        allowClear
                        options={[
                          {
                            value: "Landscapes & Sea and Sky",
                            label: "Landscapes & Sea and Sky",
                          },
                          {
                            value: "Stylised & cartoon and illustrative",
                            label: "Stylised & cartoon and illustrative",
                          },
                          {
                            value: " Abstract",
                            label: " Abstract",
                          },
                          {
                            value: " Realistic and photographic",
                            label: " Realistic and photographic",
                          },
                          {
                            value: " Classical and traditional",
                            label: " Classical and traditional",
                          },
                          {
                            value: " Surrealistic",
                            label: " Surrealistic",
                          },
                          {
                            value: " Naive",
                            label: " Naive",
                          },
                          {
                            value: " Portraiture",
                            label: " Portraiture",
                          },
                          {
                            value: " Urban",
                            label: " Urban",
                          },
                          {
                            value: " Photography",
                            label: " Photography",
                          },
                          {
                            value: " Illustration",
                            label: " Illustration",
                          },
                          {
                            value: " Conceptual",
                            label: " Conceptual",
                          },
                          {
                            value: " Digital art",
                            label: " Digital art",
                          },
                          {
                            value: " Expressionistic",
                            label: " Expressionistic",
                          },
                        ]}
                      />
                    </div>
                    <button className="btn-primary btn-search">Search</button>
                  </div>
                </div>
              </div>
            </div>
            <div className="carousel-item ">
              <img
                src={Background}
                className="card-img d-block w-100"
                alt="..."
              />
              <div className="carousel-caption d-none d-md-block">
                <h1 className="card-title text-center mt-4">
                  Decorative Coasters Made With Artificial Intelligence
                </h1>
                <h4 className="card-text text-center">
                  A Collection Of Art - Ceated By Artists Around The World -
                  Generated By
                </h4>
                <h4 className="card-text text-center">
                  Al - Printed On High Quality Coasters.
                </h4>
                <Link to="#" className="btn-read">
                  <button className="btn-primary">READ MORE</button>
                </Link>
                <div className="mb-3 mt-5 d-flex justify-content-center">
                  <div className="d-block">
                    <div className="d-flex">
                      <Select
                        defaultValue="Colour"
                        allowClear
                        options={[
                          {
                            value: "Brown",
                            label: "Brown",
                          },
                          {
                            value: "Black",
                            label: "Black",
                          },
                          {
                            value: "Blue",
                            label: "Blue",
                          },
                          {
                            value: "Green",
                            label: "Green",
                          },
                          {
                            value: "Yellow",
                            label: "Yellow",
                          },
                          {
                            value: "Orange",
                            label: "Orange",
                          },
                          {
                            value: "Red",
                            label: "Red",
                          },
                          {
                            value: "Pink",
                            label: "Pink",
                          },
                          {
                            value: "Purple",
                            label: "Purple",
                          },
                        ]}
                      />
                    </div>
                    <div className="d-flex my-2">
                      <Select
                        defaultValue="Subject"
                        allowClear
                        options={[
                          {
                            value: "Landscapes & Sea and Sky",
                            label: "Landscapes & Sea and Sky",
                          },
                          {
                            value: "People",
                            label: "People",
                          },
                          {
                            value: "Animals and Birds",
                            label: "Animals and Birds",
                          },
                          {
                            value: "Abstract",
                            label: "Abstract",
                          },
                          {
                            value: "Still Life",
                            label: "Still Life",
                          },
                          {
                            value: "Architecture and Buildings",
                            label: "Architecture and Buildings",
                          },
                          {
                            value: "Flowers and Plants",
                            label: "Flowers and Plants",
                          },
                          {
                            value: "Nudes and Erotic",
                            label: "Nudes and Erotic",
                          },
                          {
                            value: "Transport",
                            label: "Transport",
                          },
                          {
                            value: "Dogs",
                            label: "Dogs",
                          },
                          {
                            value: "Cats",
                            label: "Cats",
                          },
                          {
                            value: "Horses",
                            label: "Horses",
                          },
                          {
                            value: "London Art",
                            label: "London Art",
                          },
                          {
                            value: "Office Wall Art",
                            label: "Office Wall Art",
                          },
                          {
                            value: "Art for Interior Designers",
                            label: "Art for Interior Designers",
                          },
                          {
                            value: "Nature",
                            label: "Nature",
                          },
                          {
                            value: "Sunsets",
                            label: "Sunsets",
                          },
                          {
                            value: "Cityscapes",
                            label: "Cityscapes",
                          },
                        ]}
                      />
                    </div>
                    <div className="d-flex my-2">
                      <Select
                        defaultValue="Style"
                        allowClear
                        options={[
                          {
                            value: "Landscapes & Sea and Sky",
                            label: "Landscapes & Sea and Sky",
                          },
                          {
                            value: "Stylised & cartoon and illustrative",
                            label: "Stylised & cartoon and illustrative",
                          },
                          {
                            value: " Abstract",
                            label: " Abstract",
                          },
                          {
                            value: " Realistic and photographic",
                            label: " Realistic and photographic",
                          },
                          {
                            value: " Classical and traditional",
                            label: " Classical and traditional",
                          },
                          {
                            value: " Surrealistic",
                            label: " Surrealistic",
                          },
                          {
                            value: " Naive",
                            label: " Naive",
                          },
                          {
                            value: " Portraiture",
                            label: " Portraiture",
                          },
                          {
                            value: " Urban",
                            label: " Urban",
                          },
                          {
                            value: " Photography",
                            label: " Photography",
                          },
                          {
                            value: " Illustration",
                            label: " Illustration",
                          },
                          {
                            value: " Conceptual",
                            label: " Conceptual",
                          },
                          {
                            value: " Digital art",
                            label: " Digital art",
                          },
                          {
                            value: " Expressionistic",
                            label: " Expressionistic",
                          },
                        ]}
                      />
                    </div>
                    <button className="btn-primary btn-search">Search</button>
                  </div>
                </div>
              </div>
            </div>
            <div className="carousel-item active">
              <img
                src={Background}
                className="card-img d-block w-100"
                alt="..."
              />
              <div className="carousel-caption d-none d-md-block">
                <h1 className="card-title text-center mt-4">
                  Decorative Coasters Made With Artificial Intelligence
                </h1>
                <h4 className="card-text text-center">
                  A Collection Of Art - Ceated By Artists Around The World -
                  Generated By
                </h4>
                <h4 className="card-text text-center">
                  Al - Printed On High Quality Coasters.
                </h4>
                <Link to="#" className="btn-read">
                  <button className="btn-primary">READ MORE</button>
                </Link>
                <div className="mb-3 mt-5 d-flex justify-content-center">
                  <div className="d-block">
                    <div className="d-flex">
                      <Select
                        defaultValue="Colour"
                        allowClear
                        options={[
                          {
                            value: "Brown",
                            label: "Brown",
                          },
                          {
                            value: "Black",
                            label: "Black",
                          },
                          {
                            value: "Blue",
                            label: "Blue",
                          },
                          {
                            value: "Green",
                            label: "Green",
                          },
                          {
                            value: "Yellow",
                            label: "Yellow",
                          },
                          {
                            value: "Orange",
                            label: "Orange",
                          },
                          {
                            value: "Red",
                            label: "Red",
                          },
                          {
                            value: "Pink",
                            label: "Pink",
                          },
                          {
                            value: "Purple",
                            label: "Purple",
                          },
                        ]}
                      />
                    </div>
                    <div className="d-flex my-2">
                      <Select
                        defaultValue="Subject"
                        allowClear
                        options={[
                          {
                            value: "Landscapes & Sea and Sky",
                            label: "Landscapes & Sea and Sky",
                          },
                          {
                            value: "People",
                            label: "People",
                          },
                          {
                            value: "Animals and Birds",
                            label: "Animals and Birds",
                          },
                          {
                            value: "Abstract",
                            label: "Abstract",
                          },
                          {
                            value: "Still Life",
                            label: "Still Life",
                          },
                          {
                            value: "Architecture and Buildings",
                            label: "Architecture and Buildings",
                          },
                          {
                            value: "Flowers and Plants",
                            label: "Flowers and Plants",
                          },
                          {
                            value: "Nudes and Erotic",
                            label: "Nudes and Erotic",
                          },
                          {
                            value: "Transport",
                            label: "Transport",
                          },
                          {
                            value: "Dogs",
                            label: "Dogs",
                          },
                          {
                            value: "Cats",
                            label: "Cats",
                          },
                          {
                            value: "Horses",
                            label: "Horses",
                          },
                          {
                            value: "London Art",
                            label: "London Art",
                          },
                          {
                            value: "Office Wall Art",
                            label: "Office Wall Art",
                          },
                          {
                            value: "Art for Interior Designers",
                            label: "Art for Interior Designers",
                          },
                          {
                            value: "Nature",
                            label: "Nature",
                          },
                          {
                            value: "Sunsets",
                            label: "Sunsets",
                          },
                          {
                            value: "Cityscapes",
                            label: "Cityscapes",
                          },
                        ]}
                      />
                    </div>
                    <div className="d-flex my-2">
                      <Select
                        defaultValue="Style"
                        allowClear
                        options={[
                          {
                            value: "Landscapes & Sea and Sky",
                            label: "Landscapes & Sea and Sky",
                          },
                          {
                            value: "Stylised & cartoon and illustrative",
                            label: "Stylised & cartoon and illustrative",
                          },
                          {
                            value: " Abstract",
                            label: " Abstract",
                          },
                          {
                            value: " Realistic and photographic",
                            label: " Realistic and photographic",
                          },
                          {
                            value: " Classical and traditional",
                            label: " Classical and traditional",
                          },
                          {
                            value: " Surrealistic",
                            label: " Surrealistic",
                          },
                          {
                            value: " Naive",
                            label: " Naive",
                          },
                          {
                            value: " Portraiture",
                            label: " Portraiture",
                          },
                          {
                            value: " Urban",
                            label: " Urban",
                          },
                          {
                            value: " Photography",
                            label: " Photography",
                          },
                          {
                            value: " Illustration",
                            label: " Illustration",
                          },
                          {
                            value: " Conceptual",
                            label: " Conceptual",
                          },
                          {
                            value: " Digital art",
                            label: " Digital art",
                          },
                          {
                            value: " Expressionistic",
                            label: " Expressionistic",
                          },
                        ]}
                      />
                    </div>
                    <button className="btn-primary btn-search">Search</button>
                  </div>
                </div>
              </div>
            </div><div className="carousel-item ">
              <img
                src={Background}
                className="card-img d-block w-100"
                alt="..."
              />
              <div className="carousel-caption d-none d-md-block">
                <h1 className="card-title text-center mt-4">
                  Decorative Coasters Made With Artificial Intelligence
                </h1>
                <h4 className="card-text text-center">
                  A Collection Of Art - Ceated By Artists Around The World -
                  Generated By
                </h4>
                <h4 className="card-text text-center">
                  Al - Printed On High Quality Coasters.
                </h4>
                <Link to="#" className="btn-read">
                  <button className="btn-primary">READ MORE</button>
                </Link>
                <div className="mb-3 mt-5 d-flex justify-content-center">
                  <div className="d-block">
                    <div className="d-flex">
                      <Select
                        defaultValue="Colour"
                        allowClear
                        options={[
                          {
                            value: "Brown",
                            label: "Brown",
                          },
                          {
                            value: "Black",
                            label: "Black",
                          },
                          {
                            value: "Blue",
                            label: "Blue",
                          },
                          {
                            value: "Green",
                            label: "Green",
                          },
                          {
                            value: "Yellow",
                            label: "Yellow",
                          },
                          {
                            value: "Orange",
                            label: "Orange",
                          },
                          {
                            value: "Red",
                            label: "Red",
                          },
                          {
                            value: "Pink",
                            label: "Pink",
                          },
                          {
                            value: "Purple",
                            label: "Purple",
                          },
                        ]}
                      />
                    </div>
                    <div className="d-flex my-2">
                      <Select
                        defaultValue="Subject"
                        allowClear
                        options={[
                          {
                            value: "Landscapes & Sea and Sky",
                            label: "Landscapes & Sea and Sky",
                          },
                          {
                            value: "People",
                            label: "People",
                          },
                          {
                            value: "Animals and Birds",
                            label: "Animals and Birds",
                          },
                          {
                            value: "Abstract",
                            label: "Abstract",
                          },
                          {
                            value: "Still Life",
                            label: "Still Life",
                          },
                          {
                            value: "Architecture and Buildings",
                            label: "Architecture and Buildings",
                          },
                          {
                            value: "Flowers and Plants",
                            label: "Flowers and Plants",
                          },
                          {
                            value: "Nudes and Erotic",
                            label: "Nudes and Erotic",
                          },
                          {
                            value: "Transport",
                            label: "Transport",
                          },
                          {
                            value: "Dogs",
                            label: "Dogs",
                          },
                          {
                            value: "Cats",
                            label: "Cats",
                          },
                          {
                            value: "Horses",
                            label: "Horses",
                          },
                          {
                            value: "London Art",
                            label: "London Art",
                          },
                          {
                            value: "Office Wall Art",
                            label: "Office Wall Art",
                          },
                          {
                            value: "Art for Interior Designers",
                            label: "Art for Interior Designers",
                          },
                          {
                            value: "Nature",
                            label: "Nature",
                          },
                          {
                            value: "Sunsets",
                            label: "Sunsets",
                          },
                          {
                            value: "Cityscapes",
                            label: "Cityscapes",
                          },
                        ]}
                      />
                    </div>
                    <div className="d-flex my-2">
                      <Select
                        defaultValue="Style"
                        allowClear
                        options={[
                          {
                            value: "Landscapes & Sea and Sky",
                            label: "Landscapes & Sea and Sky",
                          },
                          {
                            value: "Stylised & cartoon and illustrative",
                            label: "Stylised & cartoon and illustrative",
                          },
                          {
                            value: " Abstract",
                            label: " Abstract",
                          },
                          {
                            value: " Realistic and photographic",
                            label: " Realistic and photographic",
                          },
                          {
                            value: " Classical and traditional",
                            label: " Classical and traditional",
                          },
                          {
                            value: " Surrealistic",
                            label: " Surrealistic",
                          },
                          {
                            value: " Naive",
                            label: " Naive",
                          },
                          {
                            value: " Portraiture",
                            label: " Portraiture",
                          },
                          {
                            value: " Urban",
                            label: " Urban",
                          },
                          {
                            value: " Photography",
                            label: " Photography",
                          },
                          {
                            value: " Illustration",
                            label: " Illustration",
                          },
                          {
                            value: " Conceptual",
                            label: " Conceptual",
                          },
                          {
                            value: " Digital art",
                            label: " Digital art",
                          },
                          {
                            value: " Expressionistic",
                            label: " Expressionistic",
                          },
                        ]}
                      />
                    </div>
                    <button className="btn-primary btn-search">Search</button>
                  </div>
                </div>
              </div>
            </div>
            <div className="carousel-item ">
              <img
                src={Background}
                className="card-img d-block w-100"
                alt="..."
              />
              <div className="carousel-caption d-none d-md-block">
                <h1 className="card-title text-center mt-4">
                  Decorative Coasters Made With Artificial Intelligence
                </h1>
                <h4 className="card-text text-center">
                  A Collection Of Art - Ceated By Artists Around The World -
                  Generated By
                </h4>
                <h4 className="card-text text-center">
                  Al - Printed On High Quality Coasters.
                </h4>
                <Link to="#" className="btn-read">
                  <button className="btn-primary">READ MORE</button>
                </Link>
                <div className="mb-3 mt-5 d-flex justify-content-center">
                  <div className="d-block">
                    <div className="d-flex">
                      <Select
                        defaultValue="Colour"
                        allowClear
                        options={[
                          {
                            value: "Brown",
                            label: "Brown",
                          },
                          {
                            value: "Black",
                            label: "Black",
                          },
                          {
                            value: "Blue",
                            label: "Blue",
                          },
                          {
                            value: "Green",
                            label: "Green",
                          },
                          {
                            value: "Yellow",
                            label: "Yellow",
                          },
                          {
                            value: "Orange",
                            label: "Orange",
                          },
                          {
                            value: "Red",
                            label: "Red",
                          },
                          {
                            value: "Pink",
                            label: "Pink",
                          },
                          {
                            value: "Purple",
                            label: "Purple",
                          },
                        ]}
                      />
                    </div>
                    <div className="d-flex my-2">
                      <Select
                        defaultValue="Subject"
                        allowClear
                        options={[
                          {
                            value: "Landscapes & Sea and Sky",
                            label: "Landscapes & Sea and Sky",
                          },
                          {
                            value: "People",
                            label: "People",
                          },
                          {
                            value: "Animals and Birds",
                            label: "Animals and Birds",
                          },
                          {
                            value: "Abstract",
                            label: "Abstract",
                          },
                          {
                            value: "Still Life",
                            label: "Still Life",
                          },
                          {
                            value: "Architecture and Buildings",
                            label: "Architecture and Buildings",
                          },
                          {
                            value: "Flowers and Plants",
                            label: "Flowers and Plants",
                          },
                          {
                            value: "Nudes and Erotic",
                            label: "Nudes and Erotic",
                          },
                          {
                            value: "Transport",
                            label: "Transport",
                          },
                          {
                            value: "Dogs",
                            label: "Dogs",
                          },
                          {
                            value: "Cats",
                            label: "Cats",
                          },
                          {
                            value: "Horses",
                            label: "Horses",
                          },
                          {
                            value: "London Art",
                            label: "London Art",
                          },
                          {
                            value: "Office Wall Art",
                            label: "Office Wall Art",
                          },
                          {
                            value: "Art for Interior Designers",
                            label: "Art for Interior Designers",
                          },
                          {
                            value: "Nature",
                            label: "Nature",
                          },
                          {
                            value: "Sunsets",
                            label: "Sunsets",
                          },
                          {
                            value: "Cityscapes",
                            label: "Cityscapes",
                          },
                        ]}
                      />
                    </div>
                    <div className="d-flex my-2">
                      <Select
                        defaultValue="Style"
                        allowClear
                        options={[
                          {
                            value: "Landscapes & Sea and Sky",
                            label: "Landscapes & Sea and Sky",
                          },
                          {
                            value: "Stylised & cartoon and illustrative",
                            label: "Stylised & cartoon and illustrative",
                          },
                          {
                            value: " Abstract",
                            label: " Abstract",
                          },
                          {
                            value: " Realistic and photographic",
                            label: " Realistic and photographic",
                          },
                          {
                            value: " Classical and traditional",
                            label: " Classical and traditional",
                          },
                          {
                            value: " Surrealistic",
                            label: " Surrealistic",
                          },
                          {
                            value: " Naive",
                            label: " Naive",
                          },
                          {
                            value: " Portraiture",
                            label: " Portraiture",
                          },
                          {
                            value: " Urban",
                            label: " Urban",
                          },
                          {
                            value: " Photography",
                            label: " Photography",
                          },
                          {
                            value: " Illustration",
                            label: " Illustration",
                          },
                          {
                            value: " Conceptual",
                            label: " Conceptual",
                          },
                          {
                            value: " Digital art",
                            label: " Digital art",
                          },
                          {
                            value: " Expressionistic",
                            label: " Expressionistic",
                          },
                        ]}
                      />
                    </div>
                    <button className="btn-primary btn-search">Search</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          
        </div>
      </div>
      <div className="row m17 px-170 d-flex flex-wrap space pt-5">
        <div className="col-md-9 pt-5">
          <h3 className="h-match">
            Match Your Cocaster To Your Interiors and Teaset.{" "}
          </h3>
          <h3 className="my-1">We have a coaster for every colour.</h3>
          <h3>Get Your Amazing Coaster Here.</h3>{" "}
          <Link to="#" className="btn-match ">
            <button className="btn-primary btn-match mt-3 mb-3">
              Match Now
            </button>
          </Link>
        </div>

        <div className="col-md-3 mb-5">
          <div className="card h100">
            <div className="card-img-overlay div-img">
              <img src={MD10} alt="" className="img-10" />
            </div>
          </div>
        </div>
      </div>
      <ArtistOfTheMonth />
      <FeatureGallery />
      <Artwork />
      <div className="px-170 artist-call  mt-4">
        <h1 className="call pt-5 pb-2">
          Calling ALL Al Artists, Sell With Us & Get Paid
        </h1>
        <h5 className="h-artists">
          Artists Can Join For Free and get Featured in Our Premium Gallery &
          Get On
        </h5>
        <h5 className="h-artists">The Artsit Of The Week On Our Homepage.</h5>
        <Link to="#" className="btn-read">
          <button className="btn-primary join">JOIN NOW</button>
        </Link>
      </div>
      <Advertisement />
      <div className="div-back">
        <div className="px-170 row gift d-flex flex-wrap space py-4">
          <div className="col-md-9 align-left">
            <div className="d-block">
              <h1 className="text-center gift-h">Gift</h1>
              <h1 className="text-center voucher-h">VOUCHER</h1>
              <h2 className="text-center special-h">
                Gift someone A Special Ai Coaster
              </h2>
              <div className="d-flex row mt-5">
                <div className="col-md-3">
                <h5>VALID FORM:</h5></div>
                <div className="col-md-9">
                <hr /></div>
              </div>
              <hr className="hr2" />
            </div>
          </div>
          <div className="col-md-9 card gift-card">
            <img src={Gift} className="card-img pt-4" alt="..." />
            <div className="card-img-overlay pt-5">
              <h2 className="card-title text-center h20">£20</h2>
            </div>
          </div>
        </div>
      </div>
      <Topics />
    </div>
  );
};

export default Home;
